name: Run SF Scanner
description: Run Code Analyzer
inputs:
  scan-format:
    description: "Scan result format"
    required: true
  category:
    description: "Category"
    required: true
  files:
    description: "Files to scan"
    required: false
    default: "./"
  output-file:
    description: "Output file name"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Setup Node"
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: "Install Salesforce CLI"
      shell: bash
      run: |
        npm install @salesforce/cli --global
        sfdx --version
        sf plugins install @salesforce/sfdx-scanner
        sfdx plugins

    - name: "Run SF Scanner"
      shell: bash
      run: |
        sf scanner run --format ${{ inputs.scan-format }} --outfile ${{ inputs.output-file }} --target ${{ inputs.files }} --category ${{ inputs.category }}
