name: Get PR Details
description: Gets the details of a PR
inputs:
  repository:
    description: "Repository name"
    required: true
  pr-number:
    description: "Scan result format"
    required: true
  github-token:
    description: "GitHub token"
    required: true
outputs:
  files:
    description: "PR files"
    value: ${{ steps.get-pr-details.outputs.FILES }}
  head-commit:
    description: "SHA of the head commit"
    value: ${{ steps.get-pr-details.outputs.HEAD_SHA }}
runs:
  using: "composite"
  steps:
    - uses: octokit/request-action@v2.x
      id: get-pr-details
      with:
        route: GET /repos/{repo}/pulls/{pull_number}
        repo: ${{ inputs.repository }}
        pull_number: ${{ inputs.pr-number }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Get Details from PR
      id: get-pr-details
      shell: bash
      run: |
        prDetails=$(echo '${{ steps.get-pr-details.outputs.data }}')
        headSha=$(echo $prDetails | jq -r '.head.sha')
        baseSha=$(echo $prDetails | jq -r '.base.sha')
        echo "headSha: $headSha"
        echo "HEAD_SHA=$headSha" >> $GITHUB_OUTPUT
        echo "baseSha: $baseSha"
        difffiles=$(git diff --name-only --diff-filter=d $baseSha $headSha)
        echo "difffiles: $difffiles"
        files=$(echo "$difffiles" | tr '\n' ',' | sed 's/,$//')
        echo "files: $files"
        echo "FILES=$files" >> $GITHUB_OUTPUT
