name: SF Scanner on PR
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  analyze-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: get-pr-details
        name: "Get PR Details"
        uses: ./.github/actions/get-pr-details
        with:
          repository: ${{ github.repository }}
          pr-number: ${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: "echo PR files: '${{ steps.get-pr-details.outputs.files }}'"
      - run: "echo HEAD SHA: '${{ steps.get-pr-details.outputs.head-commit }}'"

      - id: run-sf-scanner
        name: "Run Code Analyzer"
        uses: ./.github/actions/sf-scanner
        with:
          scan-format: json
          category: Security
          files: ${{ steps.get-pr-details.outputs.files }}
          output-file: CodeAnalyzerGeneral.json

      - run: "cat CodeAnalyzerGeneral.json"
