name: SF Scanner
on:
  workflow_dispatch:
    inputs:
      file-format:
        description: "File format of the scanner report"
        default: "html"
        type: choice
        options:
          - json
          - csv
          - html
          - xml
      category:
        description: "Category of the scan"
        default: "Security"
        type: string
jobs:
  analyze-code:
    runs-on: ubuntu-latest
    env:
      FILE_FORMAT: ${{ inputs.file-format }}
      CATEGORY: ${{ inputs.category }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: octokit/request-action@v2.x
        id: get_commits
        with:
          route: GET /repos/{repo}/commits
          repo: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: "echo latest release: '${{ steps.get_commits.outputs.data }}'"

      - id: run-sf-scanner
        name: "Run Code Analyzer"
        uses: ./.github/actions/sf-scanner
        with:
          scan-format: ${{ env.FILE_FORMAT }}
          category: ${{ env.CATEGORY }}
          output-file: CodeAnalyzerGeneral.${{ env.FILE_FORMAT }}

      - uses: actions/upload-artifact@v4
        with:
          name: SecurityReport${{ github.run_number }}
          path: ${{ github.workspace }}/CodeAnalyzerGeneral.${{ env.FILE_FORMAT }}
          retention-days: 7
